# Generated by Django 6.0.5 on 2026-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('author', models.CharField(default='Редакція', max_length=100, verbose_name='Автор')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('content', models.TextField(verbose_name='Текст статті')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва вакансії')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('location', models.CharField(max_length=100, verbose_name='Місто/Розташування')),
                ('experience', models.CharField(max_length=50, verbose_name='Досвід роботи')),
                ('salary', models.CharField(max_length=50, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Опис вакансії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
    ]
